[package]
name = "exogress-signaling"
version = "0.1.0"
authors = ["Exogress Team <team@exogress.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0.105", features = ["derive"] }
smartstring = { version  = "0.2.3", features = ["serde"] }
